server:
  port: 8083

spring:
  liquibase:
    enabled: true
    change-log: db/changelog-master.xml

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSSSS"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:file:/data/shopping-app
    driverClassName: org.h2.Driver
    username: shopping
    password: raghu

  batch:
    job:
      enabled:

  datasource.batch:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/data/shopping-app
    username: shopping
    password: raghu

  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: raghu1000.rm@gmail.com
    password: ekpkfbybmfnfmhoq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  main:
    allow-circular-references: false

  task:
    scheduling:
      pool:
        size: 5

springdoc:
  swagger-ui:
    path: /shopping-swagger
  api-docs:
    path: /shopping-api

interval: PT01H
batchJobTime: 1

batchprocesssize: 20

chat-gpt:
  api:
    key: aNKW57tCye2DAVvEEL1udNs8BOZ1HWLoGnmT6xVOZsKmNKycOZHq1g0++CvMDuIuCSZ4M7DuCkQjttMiqfzpxQ==
    model: GC0jfasJ0og2qIzkPVMTCw==
    url: KGRHjP8RPGcHt22xRTjWlkwYpBL1hwbhjfYLdu1pbitQFOcJLQp156bCyMQ+W0oQ
